// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG65K0M8d-AJW8x8k8lWVBE1sb9RXgVwE',
    appId: '1:497951815899:web:5d23f8e98da979f970b4fe',
    messagingSenderId: '497951815899',
    projectId: 'lingopanda-1c5f4',
    authDomain: 'lingopanda-1c5f4.firebaseapp.com',
    storageBucket: 'lingopanda-1c5f4.appspot.com',
    measurementId: 'G-4CGR5MCT0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8OTqNS7aWLSLY4dnXyM0EwOg_uoh87aw',
    appId: '1:497951815899:android:a5a1c22c6817875570b4fe',
    messagingSenderId: '497951815899',
    projectId: 'lingopanda-1c5f4',
    storageBucket: 'lingopanda-1c5f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8fQprV2HnEXGBs33RtkXb6vwti7oBNnI',
    appId: '1:497951815899:ios:3b8666ed5c4dd40270b4fe',
    messagingSenderId: '497951815899',
    projectId: 'lingopanda-1c5f4',
    storageBucket: 'lingopanda-1c5f4.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8fQprV2HnEXGBs33RtkXb6vwti7oBNnI',
    appId: '1:497951815899:ios:3b8666ed5c4dd40270b4fe',
    messagingSenderId: '497951815899',
    projectId: 'lingopanda-1c5f4',
    storageBucket: 'lingopanda-1c5f4.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG65K0M8d-AJW8x8k8lWVBE1sb9RXgVwE',
    appId: '1:497951815899:web:188014c883e33d6b70b4fe',
    messagingSenderId: '497951815899',
    projectId: 'lingopanda-1c5f4',
    authDomain: 'lingopanda-1c5f4.firebaseapp.com',
    storageBucket: 'lingopanda-1c5f4.appspot.com',
    measurementId: 'G-E93RRPHTCV',
  );
}
